steps:
  lint:
    image: golangci/golangci-lint:v2.1.2
    commands:
      - golangci-lint run -v --timeout 10m
    environment:
      GOPROXY:
        from_secret: goproxy_url

  build:
    image: woodpeckerci/plugin-docker-buildx:5.2.2
    settings:
      repo: registry.megpoid.dev/codestation/registry-ratelimit-exporter
      tags:
        - latest
        - "0.1.${CI_PIPELINE_NUMBER}-dev"
      cache_images: registry.assetec.org/assetec/codestation/registry-ratelimit-exporter:cache-${CI_COMMIT_BRANCH}
      registry: registry.assetec.org
      config:
        from_secret: registry_credentials
      build_args:
        CI_COMMIT_TAG: "${CI_COMMIT_TAG}"
        GOPROXY:
          from_secret: goproxy_url

when:
  event:
    - push
    - manual
  branch:
    - master
